version: '3.8'
services:
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: lerna-base:latest
    ports:
      - '3000:3000'
    environment:
      - DEV=true
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - /app/packages/frontend/node_modules
    command: npm run dev
    logging:
      driver: loki
      options:
        # for mac
        loki-url: 'http://host.docker.internal:3100/loki/api/v1/push'
        # for linux
        # loki-url: 'http://loki:3100/loki/api/v1/push'
        loki-batch-size: '400'
        loki-external-labels: container_name=frontend
    restart: unless-stopped

  auth:
    build:
      context: ./packages/auth
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: lerna-base:latest
    ports:
      - '9000:9000'
    environment:
      - DEV=true
    volumes:
      - ./packages/auth:/app/packages/auth
      - /app/pakcages/auth/node_modules
    command: npm run dev
    logging:
      driver: loki
      options:
        # for mac
        loki-url: 'http://host.docker.internal:3100/loki/api/v1/push'
        # for linux
        # loki-url: 'http://loki:3100/loki/api/v1/push'
        loki-batch-size: '400'
        loki-external-labels: container_name=auth
    restart: unless-stopped

  # logging aggregator
  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki:/etc/loki
    ports:
      - '3100:3100'
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  # dashboard
  grafana:
    image: grafana/grafana:latest
    # can change on different system
    user: '501'
    ports:
      - '3001:3000'
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - loki

  # # metrics monitoring
  # prometheus:
  #   image: prom/prometheus
  #   ports:
  #     - '9090:9090'
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   depends_on:
  #     - auth
  # volumes:
  #   elasticsearch-data:
  # grafana-data:

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb_data:/data/db

networks:
  loki:
