# this is used by github actions to build the images and push to dockerhub
version: '3.8'
services:
  # app services
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: pmcorrea/builder:latest
    image: pmcorrea/frontend:${TAG}

  auth:
    build:
      context: ./packages/auth
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: pmcorrea/builder:latest
    image: pmcorrea/auth:${TAG}

  hello:
    build:
      context: ./packages/hello-from-pod
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: pmcorrea/builder:latest
    image: pmcorrea/hello-from-pod:${TAG}

  # logging
  loki:
    image: grafana/loki:latest

  grafana:
    image: grafana/grafana:latest
