server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://137.184.138.106:32100/loki/api/v1/push

scrape_configs:
  - job_name: proxy
    static_configs:
      - targets:
          - localhost
        labels:
          job: proxy
          __path__: /var/log/access.log
