# export envs into environment, then run
# envsubst < ./secret.yml | kubectl apply -f -

apiVersion: v1
kind: Secret
metadata:
  name: digitalocean
  namespace: kube-system
stringData:
  access-token: ${do_block_storage_token}

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: default
type: Opaque
stringData:
  JWT_SECRET: ${JWT_SECRET}
  COOKIE_SECRET: ${COOKIE_SECRET}
  CLIENT_ID: ${CLIENT_ID}
  CLIENT_SECRET: ${CLIENT_SECRET}

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: ${CERT_SECRET}
  tls.key: ${CERT_KEY_SECRET}
