# export envs into environment, then run
# envsubst < ../secrets/secret.yml | kubectl apply -f -

apiVersion: v1
kind: Secret
metadata:
  name: digitalocean
  namespace: kube-system
stringData:
  access-token: ${do_block_storage_token}

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  JWT_SECRET: ${JWT_SECRET}
  COOKIE_SECRET: ${COOKIE_SECRET}
  CLIENT_ID: ${CLIENT_ID}
  CLIENT_SECRET: ${CLIENT_SECRET}
  CERT_SECRET: ${CERT_SECRET}
  CERT_KEY_SECRET: ${CERT_KEY_SECRET}
