apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: do-block-storage
provisioner: dobs.csi.digitalocean.com
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  fsType: ext4
