apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: hashicorp/http-echo
          args:
            - '-text=Hello, world!'
          ports:
            - containerPort: 5678

---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  ports:
    - port: 80
      targetPort: 5678
  selector:
    app: echo

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: echo-ingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`staging.stackheap.io`) && PathPrefix(`/echo`)
      kind: Rule
      services:
        - name: echo-service
          port: 80
