apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          # command: ['/bin/sh']
          # args: ['-c', 'while true; do sleep 30; done']
          image: pmcorrea/auth:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 9443
          env:
            - name: PORT
              value: '9443'
            - name: PROD
              value: 'true'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: JWT_SECRET
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: COOKIE_SECRET
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: CLIENT_SECRET
          volumeMounts:
            - name: cert-volume
              mountPath: '/app/packages/auth/tls/'
              readOnly: true
      volumes:
        - name: cert-volume
          secret:
            secretName: selfsigned-cert
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app: auth

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: auth
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`staging.stackheap.io`) && PathPrefix(`/auth`)
      kind: Rule
      services:
        - name: auth
          port: 443
  tls:
    secretName: selfsigned-cert

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: default
type: Opaque
stringData:
  JWT_SECRET: c29tZV9zZWNyZXQ=
  COOKIE_SECRET: c29tZV9zZWNyZXQ=
  CLIENT_ID: NTE2NDA2OTMxMzUyLWtqaWd1MnBzYjlzcGtkOGZkc3Nsa2JianQzNGJwYzh2LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  CLIENT_SECRET: R09DU1BYLU05X3RZZW10THlHQ1hOZ3JrckpicUt5cmN6bE4=
