apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: pmcorrea/auth:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: auth

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: auth
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`staging.stackheap.io`) && PathPrefix(`/auth`)
      kind: Rule
      services:
        - name: auth
          port: 3000
