version: '3'

services:
  traefik:
    image: traefik:v2.11
    command:
      - '--log.level=DEBUG'
      # - '--api.insecure=true'
      - '--providers.docker=false'
      - '--providers.file.filename=/etc/traefik/dynamic_conf.yaml'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.websecure.http.tls.certResolver=acme-resolver'
      - '--certificatesResolvers.acme-resolver.acme.email=pmcorrea@me.com'
      - '--certificatesResolvers.acme-resolver.acme.storage=/etc/traefik/acme.json'
      - '--certificatesResolvers.acme-resolver.acme.httpChallenge.entryPoint=web'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - './:/etc/traefik/'
