name: 'Dev: Build and run tests'

on:
  push:
    branches-ignore:
      - main
      - staging

jobs:
  build:
    name: 'Dev: Build and run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '21'

      - name: Install Lerna
        run: npm install --global lerna

      - name: Install project
        run: npm install

      - name: Find changed packages
        id: changed
        run: |
          echo "CHANGED_PACKAGES=$(lerna changed --all --loglevel silent)" >> $GITHUB_ENV

      - name: Run tests in changed packages
        if: env.CHANGED_PACKAGES != ''
        run: |
          echo "Changed packages: $CHANGED_PACKAGES"
          lerna run test --since main --concurrency 2

      # - name: Docker Setup Buildx
      #   uses: docker/setup-buildx-action@v3.2.0

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3.0.0
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # - name: Build and push Builder base image
      #   run: |
      #     docker build -t pmcorrea/builder:latest -f ./Dockerfile.base .
      #     docker push pmcorrea/builder:latest
      #   env:
      #     DOCKER_BUILDKIT: 1

      # - name: Build and push Docker images
      #   run: |
      #     export TAG=dev
      #     # export TAG=${{ github.sha }}
      #     echo "TAG=${TAG}" > .env
      #     docker-compose -f docker-compose.staging.yml build
      #     docker-compose -f docker-compose.staging.yml push
      #   env:
      #     IMAGE_TAG: $TAG
