name: 'Dev: Run tests'

on:
  push:
    branches:
      - dev
    paths:
      - 'packages/**'

jobs:
  build:
    name: 'Dev: Run tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [auth-service, frontend] # keep up to date

    steps:
      - name: Check out the code
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '21'

      - name: Install Lerna
        run: npm install --global lerna

      - name: Run tests
        if: github.event.push.paths == 'packages/${{ matrix.package }}/**'
        run: lerna run --scope ${{ matrix.package }} build && lerna run --scope ${{ matrix.package }} test
