name: 'Dev: Run tests'

on:
  push:
    branches:
      - dev
    paths:
      - 'packages/auth'

jobs:
  build:
    name: 'Dev: Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '21'

      - name: Install Lerna
        run: npm install --global lerna

      - name: Install packages
        run: npm install

      - name: Run tests
        run: |
          lerna run --scope auth build
          lerna run --scope auth test
