name: 'Prod: Build and Push Docker images'

on:
  workflow_run:
    workflows: ['Prod: Run tests']
    types:
      - completed
    branches:
      - main

jobs:
  build:
    name: 'Prod: Build and Push Docker images'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '21'

      - name: Install Lerna
        run: npm install --global lerna

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Log into Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Builder base image
        run: |
          docker build -t pmcorrea/builder:latest -f ./Dockerfile.base .
          docker push pmcorrea/builder:latest
        env:
          DOCKER_BUILDKIT: 1

      - name: Build and push Docker images
        run: |
          export TAG=latest
          # export TAG=${{ github.sha }}
          echo "TAG=${TAG}" > .env
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml push
        env:
          IMAGE_TAG: $TAG
