name: 'Run tests'

on:
  push:
    branches:
      - dev
      - staging
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '21'
          cache: 'npm'

      - name: Install Lerna
        run: npm install --global lerna

      - name: Cache Lerna dependencies
        uses: actions/cache@v4.0.2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/lerna.json', '**/package-lock.json', '**/npm-shrinkwrap.json') }}
          restore-keys: |
            ${{ runner.os }}-lerna-

      - name: Install packages
        run: npm install

      - name: Run auth tests
        env:
          JWT_SECRET: some_secret
          COOKIE_SECRET: some_secret
          PORT: 9000
          DATABASE_URL: postgresql://user:password@localhost:5432/mydb
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          LOG_LEVEL: trace
          SWAGGER_ENABLED: true
          PINO: pino-pretty
          DEV: true
        run: |
          lerna run --scope auth build
          lerna run --scope auth test

      - name: Run frontend tests
        run: |
          lerna run --scope frontend build
          lerna run --scope frontend test
